#!/bin/bash
/usr/sbin/gnt-cluster init \
    --vg-name=ganeti -s 172.26.31.64 \
    --master-netdev=br20 \
    -I hail \
    -H kvm:kernel_path="",initrd_path=/boot/initrd-kvmU,security_model=user,security_domain=ganetiguest,use_chroot=true,usb_mouse=tablet,serial_console=true,vnc_bind_address='0.0.0.0' \
    --backend-parameters memory=512M \ 
    --enabled-hypervisors=kvm \
    --nic-parameters link=br20 \
    ganeti.ics.loc
